### ISSUE TITLE
json: cannot unmarshal bool into Go struct field Attribute.data.attributes.triage_active of type string

### ISSUE THREAD

**Issue by chilikeys** [michael1026/inscope#2]
Hello and thank you for this tool, it comes is very handy!
Unfortunately, when I run it I get this error message and no results back:

`json: cannot unmarshal bool into Go struct field Attribute.data.attributes.triage_active of type string
`
I am not familiar with golang but it seems to me as some variable is of the wrong type perhaps?
I am using Ubuntu and go version 1.16.4.

**Comment by Dazaiii1** [comment]
I got the same problem right now :(

**Comment by Dazaiii1** [comment]
Finally I fixed this issue ,
- search for this line:  `        Triage_active                        string    json:"triage_active"`

- and replace it with : `        Triage_active                        bool    json:"triage_active"`

**Comment by michael1026** [comment]
Thank you. I'll get this fixed.

**Comment by michael1026** [comment]
This should be fixed now.

**Comment by chilikeys** [comment]
it is now working for me. Thanks a lot! :)
